start py Worker1.py
start py Worker2.py
start py Worker3.py
start py Worker4.py
start py Worker5.py
start py Worker6.py
start py Worker7.py
start py Worker8.py
start py Worker9.py
start py Worker10.py